services:
  database:
    build:
      context: ./mongodb
    container_name: mongo_database
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "5000"

  quoteserver:
    build:
      context: ./quoteserver
    ports:
      - "5001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - quoteserver
      - backend
    ports:
      - "80:80"
