services:
  database:
    build:
      context: ./mongodb
    container_name: mongo_database
    ports:
      - "27017:27017"

  backend_buy:
    build:
      context: ./backend/buy
    ports:
      - "5001"

  backend_sell:
    build:
      context: ./backend/sell
    ports:
      - "5000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_buy
      - backend_sell
    ports:
      - "80:80"
