services:
  database:
    build:
      context: ./mongodb
    container_name: mongo_database
    ports:
      - "27017:27017"

  backend_buy:
    build:
      context: ./backend
      dockerfile: ./buy/Dockerfile
    ports:
      - "5000"

  backend_sell:
    build:
      context: ./backend
      dockerfile: ./sell/Dockerfile
    ports:
      - "5000"

  quoteserver:
    build:
      context: ./quoteserver
    ports:
      - "5001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - quoteserver
      - backend_buy
      - backend_sell

    ports:
      - "80:80"
